site_name: Celeste's Girl
site_url: https://art.tightbytes.com
edit_uri: "http://127.0.0.1:8000/docs/"
use_directory_urls: true
theme:
  name: material
  logo: assets/images/logo.png
  variant: classic

  favicon: assets/images/favicon.png

  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode

    # Dark mode
    - scheme: slate
      primary: indigo
      accent: white
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/custom.css
  - stylesheets/extras.css

nav:
  - Home: index.md

  - Writing:
      - writing/index.md
      - Celeste's Girl v1: writing/1CG-1stEd.md
      - Celeste's Girl v2: writing/1CG-2ndEd.md
      - Design Structures: writing/A-Structure.md
      - Writing Emotional: writing/B-Emotions.md
      - Writing Metaphors: writing/C-Metaphors.md
      - Holding The Knife: writing/C3-HTheKnife.md
      - Canon CelestesGrl: writing/CanonBible.md
      - The Deep End-Sc23: writing/D1-Scene23r.md
      - Plotline To Study: writing/D2-ToStudy.md
      - Current Scribbles: writing/Writing.md

  - Media:
      - media/index.md
      - Music: media/Music.md
      - Video: media/Videos.md

  - Work:
      - work/index.md
      - Emily's Intelligence: work/01Emilyai.md
      - Images in ComfyUI 💋: work/02Comfyui.md
      - ArtInt Illustrations: work/03CUIllus.md
      - Making LoRAs FluxGym: work/04FluxGym.md
      - Domains Transferring: work/05DomXfer.md
      - Banners-Website Misc: work/06Banners.md
      - General Queries: work/07General.md
      - Video Scripts💛: work/08VScripts.md

plugins:
  - search
  - tags
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
