site_name: Celeste's Girl
site_url: https://art.tightbytes.com
edit_uri: "http://127.0.0.1:8000/docs/"
use_directory_urls: true
theme:
  name: material
  logo: assets/images/logo.png
  variant: classic

  favicon: assets/images/favicon.png

  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night # indigo
        name: Switch to Dark Mode

    # Dark mode
    - scheme: slate
      primary: indigo
      accent: white
      toggle:
        icon: material/weather-sunny # indigo
        name: Switch to Light Mode

  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

extra_css:
  - stylesheets/custom.css
  - stylesheets/extras.css

nav:
  - Home: index.md

  - Charlotte:
      - Charlotte/index.md
      - Celeste's Girl v1: Charlotte/1CG-1stEd.md
      - Celeste's Girl v2: Charlotte/1CG-2ndEd.md
      - Holding The Knife: Charlotte/C3-HTheKnife.md
      - Canon Bible C Grl: Charlotte/CanonBible.md
      - The Deep End-Sc23: Charlotte/D1-Scene23r.md
      - Plotline To Study: Charlotte/D2-ToStudy.md
      - Current Scribbles: Charlotte/D3-Words03.md

  - Emily:
      - Emily/index.md
      - Design Structure: Emily/A-Structure.md
      - Writing Emotions: Emily/B-Emotions.md
      - Writing Metaphors: Emily/C-Metaphors.md

  - Dev:
      - Dev/index.md
      - ArtiI Illustrious: Dev/ai-Illust.md
      - AI Imaging Models: Dev/aiModels.md
      - Banners and Stuff: Dev/Banners.md
      - Careful Ideas Now: Dev/Careful.md
      - ComfyUI Guidance: Dev/Comfyui.md
      - Domain Transfer: Dev/DomXfer.md
      - General Queries: Dev/General.md
      - Writing Fridays: Dev/WritingFri.md
      - Just Writing: Dev/Writing.md
      - Image Prompts: Dev/Prompts.md

  - Blogs:
      - blogs/index.md
      - Blog Sep25: blogs/Blog2509.md
      - Blog Oct25: blogs/Blog2510.md
      - Blog Nov25: blogs/Blog2511.md
      - Blog Dec25: blogs/Blog2512.md
      - Blog Jan26: blogs/Blog2601.md
      - Blog Feb26: blogs/Blog2602.md

  - Music:
      - music/index.md
      - Sketches: music/Sketches.md

  - Work:
      - work/index.md
      - ScratchPad: work/words01.md
      - Apr Prompt: work/words02.md
      - 2nd Person: work/Person2.md
      - AI & Emily: work/Emilyai.md
      - BBox- SEGS: work/BBoxSEGS.md
      - ComfyUI 💋: work/Comfyui.md
      - FluxGym 👭: work/FluxGym.md
      - GIMPTip 🎀: work/GimpTip.md
      - QwenPrompt: work/QwenPro.md
      - Videos💧💧: work/Videos.md
      - VScripts💛: work/VScripts.md

plugins:
  - search
  - tags
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.snippets
